"li t1, 0 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"li t2, 0 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"li t3, 0 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"li t4, 0 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"fcvt.d.w f1, t1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"li t2, 2 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t" 
"li zero, 0 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"
"loop_start: \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"  
"bge t1, %[N], loop_end \n\t"
"mul t3, t1, t2 \n\t"
"addi %[mul_cnt], %[mul_cnt], 1 \n\t"
"addi t3, t3, 1 \n\t"
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"fcvt.d.w %[pi], t3 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"  
"beqz t3, skip_divide \n\t"
"rem t4, t1, t2 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"	
"addi %[others_cnt], %[others_cnt], 1 \n\t"  
"beq t4, zero, set \n\t"
"li t4, -1 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"  
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"beq zero,zero,continue \n\t"
"set: \n\t"
"li t4,1 \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"

"continue: \n\t"
"fcvt.d.w f2, t4 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"
"fdiv.d f2, f2, %[pi] \n\t"
"addi %[div_cnt], %[div_cnt], 1 \n\t"
"skip_divide: \n\t"
"fadd.d f1, f1, f2 \n\t"
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"addi t1, t1, 1 \n\t"
"addi %[add_cnt], %[add_cnt], 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"  
"j loop_start \n\t"

"loop_end: \n\t"
"fmv.d %[pi], f1 \n\t"
"addi %[others_cnt], %[others_cnt], 1 \n\t"


